---
- hosts: all
  become: true
  
  tasks:
  - name: Install unzip
    apt:
      name: unzip
      state: present

  - name: Download awscli 
    get_url: url=https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip dest=./awscliv2.zip
    register: aws_cli_download

  - name: Unarchive a file with extra options
    unarchive:
      src: ./awscliv2.zip
      dest: /
    when: aws_cli_download.changed
    register: aws_cli_unarchive

  - name: Install awscli
    command: ./aws/install

  - name: Create test file
    command: echo "test S3 upload" > myfile.txt
  