---
# tasks file for uploadfile
- name: Update apt cache if needed
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400

- name: Install unzip
  ansible.builtin.apt:
    name: unzip
    state: present

- name: Download awscli installer
  ansible.builtin.unarchive:
    src: "{{ uploadfile_awscli_url }}"
    dest: /tmp
    remote_src: true
    creates: /tmp/aws
    mode: "0755"

- name: Run installer
  ansible.builtin.command:
  args:
    cmd: /tmp/aws/install
    creates: /usr/local/bin/aws
  notify:
    - Get awscli version

- name: Run handlers
  ansible.builtin.meta: flush_handlers

- name: Create test file
  ansible.builtin.copy:
    content: "test S3 upload"
    dest: "{{ uploadfile_file_name }}"
    mode: "0644"

- name: Check awscli version
  ansible.builtin.debug:
    var: uploadfile_aws_version.stdout
